@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json

# @name login
POST http://{{host}}/auth/login
Content-Type: {{contentType}}

{
    "username": "Gru"
}

###

@accessToken = {{login.response.body.accessToken}}
@refreshToken = {{login.response.body.refreshToken}}

# @name refreshToken
POST http://{{host}}/auth/refreshToken
Content-Type: {{contentType}}

{
    "refreshToken": "{{refreshToken}}" 
}

###

GET http://{{host}}/track
Authorization: Bearer {{accessToken}}
###

GET http://{{host}}/track
Authorization: Bearer {{accessToken}}

###
POST http://{{host}}/track
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}
{
    "name": "The New Track",
    "album": "The album of the new track",
    "artist": "The artist of the new track",
    "duration": 505,
    "artworkUrl": "https://i.ytimg.com/vi/421w1j87fEM/default.jpg",
    "audioUrl": "https://music.youtube.com/watch?v=421w1j87fEM"
}
###

GET http://{{host}}/playlist
Authorization: Bearer {{accessToken}}

###

GET http://{{host}}/playlist/4
Authorization: Bearer {{accessToken}}

###
