export const seedPlaylists = [
  {
    name: "January's Top Hits",
    creator: "Kevin",
  },
  {
    name: "March's Top Hits",
    creator: "Carl",
  },
  {
    name: "August's Top Hits",
    creator: "Stuart",
  },
  {
    name: "October's Top Hits",
    creator: "Jerry",
  },
]

export const seedTracks = [
  {
    name: "150 Bars (Ke Hip Hop Dawg)",
    artist: "Big Zulu",
    album: "Single",
    duration: 195,
    recordLabel: "Inkabi Records",
    artworkUrl: "https://i.ytimg.com/vi/-bIGv0p0kmU/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "-bIGv0p0kmU",
    },
    audioUrl: "https://music.youtube.com/watch?v=-bIGv0p0kmU",
  },
  {
    name: "Sofa Silahlane [ft. Nkosazana Daughter]",
    artist: "Wanitwa Mos, Master KG & Lowsheen",
    album: "Single",
    duration: 250,
    recordLabel: "Wanitwa Mos Entertainment",
    artworkUrl: "https://i.ytimg.com/vi/39ExO5Wcfjw/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "39ExO5Wcfjw",
    },
    audioUrl: "https://music.youtube.com/watch?v=39ExO5Wcfjw",
  },
  {
    name: "Voicemail",
    artist: "Inkabi Nation",
    album: "Single",
    duration: 335,
    recordLabel: "Inkabi Records",
    artworkUrl: "https://i.ytimg.com/vi/2SElPMuRBlg/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "2SElPMuRBlg",
    },
    audioUrl: "https://music.youtube.com/watch?v=2SElPMuRBlg",
  },
  {
    name: "Alusafani",
    artist: "Q Twins Feat. Xowla,Mduduzi Ncube & Big Zulu",
    album: "Single",
    duration: 198,
    recordLabel: "Ezase Afro",
    artworkUrl: "https://i.ytimg.com/vi/rbzm1O0v2AM/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "rbzm1O0v2AM",
    },
    audioUrl: "https://music.youtube.com/watch?v=rbzm1O0v2AM",
  },
  {
    name: "Last Last",
    artist: "Burna Boy",
    album: "Single",
    duration: 273,
    recordLabel: "Burna Boy",
    artworkUrl: "https://i.ytimg.com/vi/421w1j87fEM/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "421w1j87fEM",
    },
    audioUrl: "https://music.youtube.com/watch?v=421w1j87fEM",
  },
  {
    name: "Quantham (First Load)",
    artist: "Kwesta",
    album: "Single",
    duration: 304,
    recordLabel: "KwestaVEVO",
    artworkUrl: "https://i.ytimg.com/vi/GkQGp7tytGQ/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "GkQGp7tytGQ",
    },
    audioUrl: "https://music.youtube.com/watch?v=GkQGp7tytGQ",
  },
  {
    name: "‘Pink Venom’ M/V",
    artist: "BLACKPINK",
    album: "Single",
    duration: 235,
    recordLabel: "BLACKPINK",
    artworkUrl: "https://i.ytimg.com/vi/gQlMMD8auMs/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "gQlMMD8auMs",
    },
    audioUrl: "https://music.youtube.com/watch?v=gQlMMD8auMs",
  },
  {
    name: "Dali Nguwe (ft Nkosazana Daughter, Basetsana, Obeey Amor)",
    artist: "Wanitwa Mos & Master KG",
    album: "Single",
    duration: 314,
    recordLabel: "Wanitwa Mos Entertainment",
    artworkUrl: "https://i.ytimg.com/vi/IXUOPJDnzRg/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "IXUOPJDnzRg",
    },
    audioUrl: "https://music.youtube.com/watch?v=IXUOPJDnzRg",
  },
  {
    name: "Buga",
    artist: "Kizz Daniel, Tekno",
    album: "Single",
    duration: 306,
    recordLabel: "KizzDanielVEVO",
    artworkUrl: "https://i.ytimg.com/vi/bLF90M96m2Q/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "bLF90M96m2Q",
    },
    audioUrl: "https://music.youtube.com/watch?v=bLF90M96m2Q",
  },
  {
    name: "9umba, TOSS & Mdoovar [Ft. Sir Trill, Sino Msolo, Lady Du, Young Stunna & Slade] (Video)",
    artist: "uMlando",
    album: "Single",
    duration: 304,
    recordLabel: "9umba 9umba",
    artworkUrl: "https://i.ytimg.com/vi/4zxBwA3xOsc/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "4zxBwA3xOsc",
    },
    audioUrl: "https://music.youtube.com/watch?v=4zxBwA3xOsc",
  },
  {
    name: "Ithuba",
    artist: "Lwah Ndlunkulu (Ft. Siya Ntuli)",
    album: "Single",
    duration: 328,
    recordLabel: "Inkabi Records",
    artworkUrl: "https://i.ytimg.com/vi/_YkouBp8O1A/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "_YkouBp8O1A",
    },
    audioUrl: "https://music.youtube.com/watch?v=_YkouBp8O1A",
  },
  {
    name: "Reece",
    artist: "Blxckie & A",
    album: "Single",
    duration: 314,
    recordLabel: "blxckie",
    artworkUrl: "https://i.ytimg.com/vi/6XhR7_eR_9k/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "6XhR7_eR_9k",
    },
    audioUrl: "https://music.youtube.com/watch?v=6XhR7_eR_9k",
  },
  {
    name: "Big Flexa ft. C'buda M, Alfa Kat, Banaba Des, Sdida & Man T",
    artist: "@Costa Titch",
    album: "Single",
    duration: 250,
    recordLabel: "Costa Titch",
    artworkUrl: "https://i.ytimg.com/vi/8g0v2SDe6MU/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "8g0v2SDe6MU",
    },
    audioUrl: "https://music.youtube.com/watch?v=8g0v2SDe6MU",
  },
  {
    name: "Thula",
    artist: "Lowsheen, Master KG & Nkosazana Daughter",
    album: "Single",
    duration: 184,
    recordLabel: "Wanitwa Mos Entertainment",
    artworkUrl: "https://i.ytimg.com/vi/UCjdmPhDMu8/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "UCjdmPhDMu8",
    },
    audioUrl: "https://music.youtube.com/watch?v=UCjdmPhDMu8",
  },
  {
    name: "Magear [Feat Mr Brown]",
    artist: "Makhadzi",
    album: "Single",
    duration: 225,
    recordLabel: "Openmic Productions",
    artworkUrl: "https://i.ytimg.com/vi/frsG6ho0fXk/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "frsG6ho0fXk",
    },
    audioUrl: "https://music.youtube.com/watch?v=frsG6ho0fXk",
  },
  {
    name: "Amagents",
    artist: "Samthing Soweto",
    album: "Single",
    duration: 318,
    recordLabel: "Samthing Soweto",
    artworkUrl: "https://i.ytimg.com/vi/Tp_j0pu9ScQ/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "Tp_j0pu9ScQ",
    },
    audioUrl: "https://music.youtube.com/watch?v=Tp_j0pu9ScQ",
  },
  {
    name: "Mark & TpZee",
    artist: "Q",
    album: "Single",
    duration: 251,
    recordLabel: "Cloud9ne Entertainment",
    artworkUrl: "https://i.ytimg.com/vi/ORCCxt1xlLI/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "ORCCxt1xlLI",
    },
    audioUrl: "https://music.youtube.com/watch?v=ORCCxt1xlLI",
  },
  {
    name: "Abo Mvelo (Visualizer) ft. Mellow & Sleazy and M.J",
    artist: "Daliwonga",
    album: "Single",
    duration: 255,
    recordLabel: "Daliwonga",
    artworkUrl: "https://i.ytimg.com/vi/zGcrYxWB_As/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "zGcrYxWB_As",
    },
    audioUrl: "https://music.youtube.com/watch?v=zGcrYxWB_As",
  },
  {
    name: "Phakade Lami ft. Sha Sha, Ami Faku",
    artist: "Nomfundo Moh",
    album: "Single",
    duration: 235,
    recordLabel: "NomfundoMohVEVO",
    artworkUrl: "https://i.ytimg.com/vi/TtYubd-C_Yo/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "TtYubd-C_Yo",
    },
    audioUrl: "https://music.youtube.com/watch?v=TtYubd-C_Yo",
  },
  {
    name: "Angsakhoni",
    artist: "Mduduzi Ncube",
    album: "Single",
    duration: 230,
    recordLabel: "Inkabi Records",
    artworkUrl: "https://i.ytimg.com/vi/tlXM-8TB-k0/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "tlXM-8TB-k0",
    },
    audioUrl: "https://music.youtube.com/watch?v=tlXM-8TB-k0",
  },
  {
    name: "Jehovah Ft Zuma",
    artist: "S'Villa",
    album: "Single",
    duration: 184,
    recordLabel: "Ambitiouz Entertainment",
    artworkUrl: "https://i.ytimg.com/vi/l7iV-N41PdU/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "l7iV-N41PdU",
    },
    audioUrl: "https://music.youtube.com/watch?v=l7iV-N41PdU",
  },
  {
    name: "Ngiyamthanda  feat. Lowsheen",
    artist: "MaWhoo & Master KG",
    album: "Single",
    duration: 341,
    recordLabel: "Wanitwa Mos Entertainment",
    artworkUrl: "https://i.ytimg.com/vi/k02ce-oREKY/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "k02ce-oREKY",
    },
    audioUrl: "https://music.youtube.com/watch?v=k02ce-oREKY",
  },
  {
    name: "Soft Life",
    artist: "Nomfundo Moh",
    album: "Single",
    duration: 256,
    recordLabel: "NomfundoMohVEVO",
    artworkUrl: "https://i.ytimg.com/vi/JxJiUGfv_E4/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "JxJiUGfv_E4",
    },
    audioUrl: "https://music.youtube.com/watch?v=JxJiUGfv_E4",
  },
  {
    name: "Ivolovolo",
    artist: "Big Zulu (Ft. Xowla)",
    album: "Single",
    duration: 193,
    recordLabel: "Inkabi Records",
    artworkUrl: "https://i.ytimg.com/vi/uEzMWuRMjW4/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "uEzMWuRMjW4",
    },
    audioUrl: "https://music.youtube.com/watch?v=uEzMWuRMjW4",
  },
  {
    name: "Uthando  feat. Nokwazi, Lowsheen, Caltonic SA",
    artist: "DJ Ngwazi & Master KG",
    album: "Single",
    duration: 285,
    recordLabel: "Wanitwa Mos Entertainment",
    artworkUrl: "https://i.ytimg.com/vi/3B31jj--yO8/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "3B31jj--yO8",
    },
    audioUrl: "https://music.youtube.com/watch?v=3B31jj--yO8",
  },
  {
    name: "Put Your Hands Up (Visualizer) ft. Mousse T.",
    artist: "Cassper Nyovest",
    album: "Single",
    duration: 188,
    recordLabel: "CassperNyovestVEVO",
    artworkUrl: "https://i.ytimg.com/vi/_U1Fi8EzaRc/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "_U1Fi8EzaRc",
    },
    audioUrl: "https://music.youtube.com/watch?v=_U1Fi8EzaRc",
  },
  {
    name: "For My Hand feat. Ed Sheeran",
    artist: "Burna Boy",
    album: "Single",
    duration: 182,
    recordLabel: "Burna Boy",
    artworkUrl: "https://i.ytimg.com/vi/EDZ25anwgjc/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "EDZ25anwgjc",
    },
    audioUrl: "https://music.youtube.com/watch?v=EDZ25anwgjc",
  },
  {
    name: "Calm Down",
    artist: "Rema",
    album: "Single",
    duration: 295,
    recordLabel: "Rema",
    artworkUrl: "https://i.ytimg.com/vi/CQLsdm1ZYAw/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "CQLsdm1ZYAw",
    },
    audioUrl: "https://music.youtube.com/watch?v=CQLsdm1ZYAw",
  },
  {
    name: "Sibaningi (Visualizer) ft. Kwesta",
    artist: "Nomfundo Moh",
    album: "Single",
    duration: 254,
    recordLabel: "NomfundoMohVEVO",
    artworkUrl: "https://i.ytimg.com/vi/ZnrWXf5yuU8/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "ZnrWXf5yuU8",
    },
    audioUrl: "https://music.youtube.com/watch?v=ZnrWXf5yuU8",
  },
  {
    name: '"Electricity"',
    artist: "Pheelz x Davido",
    album: "Single",
    duration: 321,
    recordLabel: "Pheelz",
    artworkUrl: "https://i.ytimg.com/vi/RhS0aKygDww/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "RhS0aKygDww",
    },
    audioUrl: "https://music.youtube.com/watch?v=RhS0aKygDww",
  },
  {
    name: "Bietjie Benoni",
    artist: "Lianie May",
    album: "Single",
    duration: 208,
    recordLabel: "Lianie May",
    artworkUrl: "https://i.ytimg.com/vi/y6pBtf9xdVs/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "y6pBtf9xdVs",
    },
    audioUrl: "https://music.youtube.com/watch?v=y6pBtf9xdVs",
  },
  {
    name: "Nomathemba ft Nkosazana Daughter, Sir Trill & Soa Mattrix | Official Video | Amapiano",
    artist: "Dj Givy Baby",
    album: "Single",
    duration: 200,
    recordLabel: "DJ Givy Baby",
    artworkUrl: "https://i.ytimg.com/vi/JnNWt7vLCtc/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "JnNWt7vLCtc",
    },
    audioUrl: "https://music.youtube.com/watch?v=JnNWt7vLCtc",
  },
  {
    name: "Give Me Jesus(feat. Mzweshper_sa)",
    artist: "Senior Oat",
    album: "Single",
    duration: 246,
    recordLabel: "Senior Oat Official",
    artworkUrl: "https://i.ytimg.com/vi/DbaZtPx8Ccg/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "DbaZtPx8Ccg",
    },
    audioUrl: "https://music.youtube.com/watch?v=DbaZtPx8Ccg",
  },
  {
    name: "Hold My Hand (From “Top Gun: Maverick”)",
    artist: "Lady Gaga",
    album: "Single",
    duration: 249,
    recordLabel: "LadyGagaVEVO",
    artworkUrl: "https://i.ytimg.com/vi/O2CIAKVTOrc/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "O2CIAKVTOrc",
    },
    audioUrl: "https://music.youtube.com/watch?v=O2CIAKVTOrc",
  },
  {
    name: "Sunshine",
    artist: "Tyga, Jhené Aiko, Pop Smoke",
    album: "Single",
    duration: 318,
    recordLabel: "TygaVEVO",
    artworkUrl: "https://i.ytimg.com/vi/FTpohtXaJcM/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "FTpohtXaJcM",
    },
    audioUrl: "https://music.youtube.com/watch?v=FTpohtXaJcM",
  },
  {
    name: "Tanzania [Feat. Sino Msolo & Boibizza]",
    artist: "Uncle Waffles and Tony Duardo",
    album: "Single",
    duration: 276,
    recordLabel: "UncleWaffles Official",
    artworkUrl: "https://i.ytimg.com/vi/zi7kX1jkRuA/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "zi7kX1jkRuA",
    },
    audioUrl: "https://music.youtube.com/watch?v=zi7kX1jkRuA",
  },
  {
    name: "Selema (Po Po) | Amapiano",
    artist: "Musa Keys & Loui",
    album: "Single",
    duration: 282,
    recordLabel: "MUSA KEYS",
    artworkUrl: "https://i.ytimg.com/vi/GUfphAcgjLA/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "GUfphAcgjLA",
    },
    audioUrl: "https://music.youtube.com/watch?v=GUfphAcgjLA",
  },
  {
    name: "Thula,[Official,Lyric,Video],Lowsheen,Master,KG,&,Nkosazana,Daughter",
    artist:
      "Thula [Official Lyric Video] Lowsheen,Master KG & Nkosazana Daughter",
    album: "Single",
    duration: 323,
    recordLabel: "Wanitwa Mos Entertainment",
    artworkUrl: "https://i.ytimg.com/vi/xjj9m_mIyIk/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "xjj9m_mIyIk",
    },
    audioUrl: "https://music.youtube.com/watch?v=xjj9m_mIyIk",
  },
  {
    name: "I Am Grateful",
    artist: "Spirit Of Praise 8 ft Mmatema",
    album: "Single",
    duration: 298,
    recordLabel: "Spirittunez",
    artworkUrl: "https://i.ytimg.com/vi/Qwc7R2S7C1g/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "Qwc7R2S7C1g",
    },
    audioUrl: "https://music.youtube.com/watch?v=Qwc7R2S7C1g",
  },
  {
    name: "Bandana",
    artist: "Fireboy DML & Asake",
    album: "Single",
    duration: 331,
    recordLabel: "Fireboy DML",
    artworkUrl: "https://i.ytimg.com/vi/gCLUIzOsgGg/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "gCLUIzOsgGg",
    },
    audioUrl: "https://music.youtube.com/watch?v=gCLUIzOsgGg",
  },
  {
    name: "Banyana Ke Bafana (Visualizer)ft. LuuDadeeja & Nobantu Vilakazi",
    artist: "Pabi Cooper, Focalistic and Ch'cco",
    album: "Single",
    duration: 212,
    recordLabel: "Pabi Cooper",
    artworkUrl: "https://i.ytimg.com/vi/AOTS2R6M9p0/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "AOTS2R6M9p0",
    },
    audioUrl: "https://music.youtube.com/watch?v=AOTS2R6M9p0",
  },
  {
    name: "Iy'ntsimbi Zase Envy",
    artist: "Reece Madlisa & Zuma",
    album: "Single",
    duration: 348,
    recordLabel: "Reece Madlisa & Zuma",
    artworkUrl: "https://i.ytimg.com/vi/_vOwxTqeRkY/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "_vOwxTqeRkY",
    },
    audioUrl: "https://music.youtube.com/watch?v=_vOwxTqeRkY",
  },
  {
    name: "Ngathwala Ngaye  ft. Mondli Ngcobo",
    artist: "Kelly Khumalo",
    album: "Single",
    duration: 339,
    recordLabel: "KellyKhumaloVEVO",
    artworkUrl: "https://i.ytimg.com/vi/R-gk-R-oxGU/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "R-gk-R-oxGU",
    },
    audioUrl: "https://music.youtube.com/watch?v=R-gk-R-oxGU",
  },
  {
    name: "Mama",
    artist: "Aymos",
    album: "Single",
    duration: 249,
    recordLabel: "Aymos ",
    artworkUrl: "https://i.ytimg.com/vi/GRsSq6KJTEY/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "GRsSq6KJTEY",
    },
    audioUrl: "https://music.youtube.com/watch?v=GRsSq6KJTEY",
  },
  {
    name: "Koue Hande",
    artist: "Juan Boucher",
    album: "Single",
    duration: 265,
    recordLabel: "REAL MUSIC - VONK MUSIEK",
    artworkUrl: "https://i.ytimg.com/vi/uh1G17LH058/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "uh1G17LH058",
    },
    audioUrl: "https://music.youtube.com/watch?v=uh1G17LH058",
  },
  {
    name: "Vegas (From the Original Motion Picture Soundtrack ELVIS)",
    artist: "Doja Cat",
    album: "Single",
    duration: 180,
    recordLabel: "dojacatVEVO",
    artworkUrl: "https://i.ytimg.com/vi/QZp2biJul1c/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "QZp2biJul1c",
    },
    audioUrl: "https://music.youtube.com/watch?v=QZp2biJul1c",
  },
  {
    name: "Amaphiko 2.0 ft Yanga Chief",
    artist: "Siphesihle Sikhakhane",
    album: "Single",
    duration: 209,
    recordLabel: "DJs Production TV",
    artworkUrl: "https://i.ytimg.com/vi/tslOLFj0D4Q/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "tslOLFj0D4Q",
    },
    audioUrl: "https://music.youtube.com/watch?v=tslOLFj0D4Q",
  },
  {
    name: "Ma Yellowbone [Feat Prince Benza]",
    artist: "Makhadzi",
    album: "Single",
    duration: 215,
    recordLabel: "Openmic Productions",
    artworkUrl: "https://i.ytimg.com/vi/DDIkDkYMH0E/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "DDIkDkYMH0E",
    },
    audioUrl: "https://music.youtube.com/watch?v=DDIkDkYMH0E",
  },
  {
    name: "5 4 3 2 1",
    artist: "Offset",
    album: "Single",
    duration: 188,
    recordLabel: "OFFSETYRN",
    artworkUrl: "https://i.ytimg.com/vi/ZAiQP7NPibo/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "ZAiQP7NPibo",
    },
    audioUrl: "https://music.youtube.com/watch?v=ZAiQP7NPibo",
  },
  {
    name: "Ilanga Music Video",
    artist: "Blaq Diamond",
    album: "Single",
    duration: 298,
    recordLabel: "BLAQ DIAMOND",
    artworkUrl: "https://i.ytimg.com/vi/zn-WhKQtkSk/default.jpg",
    resourceId: {
      kind: "youtube#video",
      videoId: "zn-WhKQtkSk",
    },
    audioUrl: "https://music.youtube.com/watch?v=zn-WhKQtkSk",
  },
];
